In [2]:
# If you want to use a package, import it firstly.
import numpy as np

# 1. Create array/matrix

In [3]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
arr3 = np.array([
    [[1,2,3,4,5],[6,7,8,9,10]],
    [[1,2,3,4,5],[6,7,8,9,10]]])
print(arr3)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


### The type of the array can also be explicitly specified at creation time.

In [7]:
arr1 = np.array([1,2,3,4,5], dtype=float)
print(arr1)
print(arr1.dtype)

[1. 2. 3. 4. 5.]
float64


### Create an array only giving its shape.

In [8]:
print(np.zeros((3)))
print(np.ones((2,5)))
print(np.empty((10,3)))

[0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Creating sequences of numbers.

In [9]:
print(np.arange(10, 30, 5)) # step interval: 5
print(np.linspace(10, 30, 4)) # number of elements: 4

[10 15 20 25]
[10.         16.66666667 23.33333333 30.        ]


### Printing arrays.

In [6]:
print(np.arange(10,20))

[10 11 12 13 14 15 16 17 18 19]


# 2. Array Basic Operations

### Use reshape to change the "shape" of an array.

In [11]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array(([
    [[1,2,3,4,5],[6,7,8,9,10]],
    [[1,2,3,4,5],[6,7,8,9,10]]]))
print(arr1.shape)
print(arr2.shape)

(2, 5)
(2, 2, 5)


In [13]:
print(arr1.reshape((5,2))) #把所有的数值平铺开来，换成想要的样子
print(arr1.reshape((10)))  #平铺
print(arr1.reshape((5,-1)))#比如总共有N个，第一位为5，第二位为N/5

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Arithmetic operation of arrays are straightforward.

In [14]:
a = np.array( [20,30,40,50] )
b = np.ones(4)
print(a+b)
print(a-b)
np.sin(a)

[21. 31. 41. 51.]
[19. 29. 39. 49.]


array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [2]:
# elementwise functions are provided by numpy.
import math
math.sin(30)

-0.9880316240928618

In [15]:
# different with python--> array的区别
print([1,2,3,4,5] * 3)
print(np.array([1,2,3,4,5]) * 3)#只有NP Array才能是普通R里面的array算法，如果是python中array就会变样。

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]


### Aggregate functions can be applied on specific axis.

In [12]:
b = np.arange(12).reshape(3,4)#axis=0,that 3 will disappear，安排上了
print(b)
print(b.sum()).
print(b.sum(axis=0)) #aggregate across the rows 相当于 y
print(b.sum(axis=1)) #aggregate across the columns is x axis

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


### Boardcasting
When operands with numpy function involved do not have exactly the same shape. Numpy tries to boardcast one of the operands to make the sizes of all arrays match, so elementwise operations can be performed.

Rule 1: If all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

Rule 2: Arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension, by expanding the value along that dimension.

总之，要想进行Boardcasting，只有两种情况，一种是随便一个东西和dimension为1的，就是1x1这种。结果不言而喻，和矩阵乘法除法相同。加减法可以理解成点加。或者其中一个

In [25]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
print(a * b)

[2. 4. 6.]


In [26]:
a=np.array([1,2])
b=np.array([1,2,3])#Broadcasting的一种错误示范。
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [27]:
a = np.array([0.0, 10.0, 20.0, 30.0]).reshape(4,-1)
b = np.array([1.0, 2.0, 3.0])
print(a)
print(b)
print(a+b）#只要其中一个是1就可以进行

[[ 0.]
 [10.]
 [20.]
 [30.]]
[1. 2. 3.]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# 3. Indexing, Slicing, Stacking and Iterating

### Indexing

In [11]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
print(a[0])#这里第一排是0
print(a[-1])
print(a[0:2])

1
[ 8  9 10 11]
[[0 1 2 3]
 [4 5 6 7]]


### Slicing

In [17]:
print(a[1,1])
print(a[0:2, 0:2])
print(a[0:2, :])
print(a[:, 0:2])

5
[[0 1]
 [4 5]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]
 [8 9]]


More fancy indexing and index tricks can be found in Numpy Tutorial: https://numpy.org/devdocs/user/quickstart.html

### Stacking

In [18]:
a = np.array([[ 8.,  8.],
       [ 0.,  0.]])
b = np.array([[ 1.,  8.],
       [ 0.,  4.]])
print(np.vstack((a,b))) #vertically
print(np.hstack((a,b))) #horizontally

[[8. 8.]
 [0. 0.]
 [1. 8.]
 [0. 4.]]
[[8. 8. 1. 8.]
 [0. 0. 0. 4.]]


### Iterating

In [19]:
for row in a:
    print(row)

[8. 8.]
[0. 0.]


In [20]:
for element in a.flat:
    print(element)

8.0
8.0
0.0
0.0


Python comprehension (A trick to generate your list)

In [21]:
print([element for element in a.flat])

[8.0, 8.0, 0.0, 0.0]
